### ISSUE TITLE
Practica 3 Visual Studio UX UI - Equipo

### ISSUE THREAD

**Issue by KevCH24** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-4as_coders#1]
[Practica 3 Visual Studio UX UI - Trabajo en equipo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-4as_coders/files/14348960/Practica.3.Visual.Studio.UX.UI.-.Trabajo.en.equipo.pdf)

**Comment by josealfredo79** [comment]
Calificacion...???

**Comment by AricelCastro** [comment]
Nuestro equipo le da una calificación de 100 que corresponde a 20/20 ya que cuenta con todos los criterios que se pide en la rúbrica contiene las imágenes señalas y está estructurado correctamente

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
